bindsym --locked XF86AudioPlay exec dms ipc call mpris playPause
bindsym --locked XF86AudioStop exec dms ipc call mpris stop
bindsym XF86AudioNext exec dms ipc call mpris next
bindsym XF86AudioPrev exec dms ipc call mpris previous